### ISSUE TITLE
BCF из ЦКС

### ISSUE THREAD

**Issue by GlabetsPasha** [tyan/BCFierForRenga#16]
![photo_2024-08-14_17-09-27](https://github.com/user-attachments/assets/b25e58c9-b043-4fe5-804a-0d3c7a8522d2)
![photo_2024-08-14_17-09-20](https://github.com/user-attachments/assets/2f6ae6f0-9bd5-4bca-9067-a353f1e824d1)

Здравствуйте! Сделал файл BCF из ПО ЦКС и при добавлении файла в плагин выдает такие ошибки. Пробовал версии и 2.1 и 3.0

**Comment by tyan** [comment]
Здравствуйте, пришлите пожалуйста файлы BCF воспроизведения. Судя по тексту ошибки есть проблема парсинга. Посмотрим на каком этапе и почему она возникает.

Спасибо за обратную связь!

**Comment by GlabetsPasha** [comment]
[Арматура_05.08.2024 16_19_BCF 3.0.bcf.zip](https://github.com/user-attachments/files/16621676/_05.08.2024.16_19_BCF.3.0.bcf.zip)

**Comment by tyan** [comment]
У приведенных файлов неверная схема формата BCF. Как для 2.1, так и для 3.0. Элемент Project находится в корне XML, тогда как должен находиться в корневом элементе ProjectExtension (для версии 2.1) или в корневом элементе ProjectInfo (для версии 3.0). Никаких упоминаний о том, что эти элементы можно опустить в стандарте я не нашел. 

- [Вот ссылка](https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/project.xsd) на валидную схему xml в официальном репо BuildingSmart.
- Проверить файл project.bcfp из присланных BCF можно в любом валидаторе XML схемы, например [здесь](https://www.liquid-technologies.com/online-xsd-validator).

Попробую написать разработчикам и сделать нормальную обработку ошибок в плагине.

**Comment by tyan** [comment]
Разработчики подтвердили, что есть ошибка. Будут править.

**Comment by tyan** [comment]
Решил оставить исходный вид сообщений. Он более информативный для разбора проблем.
